### ISSUE TITLE
HtmlImageElement missing bindings for onload

### ISSUE THREAD

**Issue by jlrickert** [tinymce/rescript-webapi#85]
I am trying to draw an image onto a canvas.  This is what I am trying to do:

```rescript
open Webapi.Canvas
open Webapi.Canvas.Canvas2d
open Webapi.Dom

let canvasEl = document->Document.createElement("canvas")
let ctx = canvasEl->CanvasElement.getContext2d

let image = HtmlImageElement.make()
image->HtmlImageElement.setSrc("image.png")
image->HtmlImageElement.onloadSet(() => {
  ctx->drawImage(image->CanvasImageSource.ofImage, ~dx=0.0, ~dy=0.0)
})
```

There are two things missing here,  `CanvasImageSource` and `onloadSet`.  The `CanvasImageSource` is related to issue #62 and pr #83.  `onloadSet` is related to [GlobalEventHandlers.onload](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload) and is part of the [GlobalEventHandlers](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers) mixin.

**Comment by TheSpyder** [comment]
What is the JS equivalent of what you're trying to do? Can't you use [`addLoadEventListener`](https://github.com/tinymce/rescript-webapi/blob/18d9d553201d575fa8e194d3370298b556b28747/src/Webapi/Dom/Webapi__Dom__EventTarget.res#L39-L41)?

In general we don't support the "set function as a property" event handlers such as `image.onload`, since we consider `image.addEventListener('load', ...)` to be the more correct way to manage events.

**Comment by jlrickert** [comment]
I wasn't aware of `addLoadEventListener`.  I was going off of the example at https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap#example where they are mutation `onload` directly.
